package:
  name: bsplyne
  version: "1.0.1"

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.9
    - setuptools
    - wheel
  run:
    - python >=3.9
    - numpy >=1.20
    - numba >=0.55
    - scipy >=1.8
    - matplotlib >=3.5
    - meshio >=5.0
    - tqdm >=4.60

test:
  imports:
    - bsplyne

about:
  home: https://github.com/Dorian210/bsplyne
  license: CeCILL-2.1
  summary: "N-dimensional B-spline library for numerical mechanics and geometry"
