{% set version = "1.0.2" %}

package:
  name: bsplyne
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bsplyne/bsplyne-{{ version }}.tar.gz
  # curl -L <url> | sha256sum
  sha256: 509f12c079869bec139f13835688c492ec7d2c13bfbfe6ad586552a01e78cf4d

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.9
    - setuptools
    - wheel
  run:
    - python >=3.9
    - numpy >=1.20
    - numba >=0.55
    - scipy >=1.8
    - matplotlib >=3.5
    - meshio >=5.0
    - tqdm >=4.60

test:
  imports:
    - bsplyne

about:
  home: https://github.com/Dorian210/bsplyne
  license: CeCILL-2.1
  summary: "N-dimensional B-spline library for numerical mechanics and geometry"
